before_script:
  - wget ftp://ftp.gnu.org/gnu/octave/octave-3.8.0.tar.bz2
  - tar -xvf octave-3.8.0.tar.bz2
  - cd octave-3.8.0
  - sudo apt-get build-dep octave
  - ./configure
  - make
  - sudo make install
script:
  - sh -c "octave tests/runalltests.m"

notifications:
  email: false
