before_script:
  - sudo apt-add-repository ppa:octave/stable --yes
  - sudo apt-get update -y
  - sudo apt-get install octave --force-yes
  - sudo apt-get install liboctave-dev -y
script:
  - sh -c "octave tests/runalltests.m"

notifications:
  email: false
